### ISSUE TITLE
Orca step 'residential_developer' crashing during simulation

### ISSUE THREAD

**Issue by stefancoe** [psrc/urbansim2#120]
@hanase:
On line 180 in developer.py:
df = df[df.max_profit_far > 0]

df here is the passed in table called 'feasibility" and max_profit_far is not available because df is a multi-indexed (leveled) table where the top level indices are land use types such as 'mix_off_res.' Each of these have columns that include 'max_profit_far'. 

Should the land use levels be removed and formed into a column?

**Comment by hanase** [comment]
Stefan, I have done some work on the developer model in the branch called newdeveloper. Not sure about this specific problem. There is much more work to do on this model (I'll forward you Scott's message). The main thing now is to make it pass without an error (or disable the models for now). This is the largest nut to crack ;-)

**Comment by stefancoe** [comment]
Thanks Hana. I am going to turn this model off for now and focus on getting hlcm & wplcm to work. 

I did get the residential_developer model to run by un-commenting the first line and removing None from the second line. But it seems like model is still under development so will keep off. 
utils.run_developer(#feasibility.local.residential_forms,
                        None,
                        households,
                        buildings,
                        "residential_units",
                        parcels.parcel_size,
                        parcels.ave_unit_size,
                        parcels.residential_units,
                        feasibility,
                        year=year,
                        target_vacancy=.15,
                        #form_to_btype_callback=random_type,
                        add_more_columns_callback=add_extra_columns,
                        bldg_sqft_per_job=400.0)

**Comment by stefancoe** [comment]
I don't think this is an issue anymore.
