### ISSUE TITLE
Create work at home model

### ISSUE THREAD

**Issue by stefancoe** [psrc/urbansim2#121]
@hanase - Do you know if there is a way to run a binary choice model with the existing Urbansim2 statistical models? Thanks!
https://udst.github.io/urbansim/models/statistical.html#api

**Comment by hanase** [comment]
I don't. And I'm not sure how much the DCM API is going to change after merging with the UDST choicemodels package. You might ask this on the discussion forum: http://discussion.urbansim.com/

**Comment by stefancoe** [comment]
Just an update- i was able to implement a work at home model (estimate & simulate) using this:\
https://github.com/UDST/choicemodels/blob/master/choicemodels/choicemodels.py

The next step is to implement it in a clean/generic way. I was thinking about using the following as a template and then maybe udst would be interested in folding into urbansim at some point. 

https://github.com/UDST/urbansim/blob/master/urbansim/models/dcm.py

**Comment by stefancoe** [comment]
I started implementing this by using the dcm class and modifying it to support [binary logit](https://github.com/psrc/urbansim2/blob/stefan_dev/psrc_urbansim/binary_discrete_choice.py)
 So far I have implemented estimation, but still need to finish simulation/predict. Please see this commit:
https://github.com/psrc/urbansim2/commit/343df75c4338fd3e53def045b0d4cb5df12c8d8d

A couple of things:

- Like all the other models, the code reads a [spec file](https://github.com/psrc/urbansim2/blob/stefan_dev/configs/wahcm.yaml), performs estimation, and writes out a file with [coefficients and fit summaries](https://github.com/psrc/urbansim2/blob/stefan_dev/configs/wplcmcoef.yaml).

- I decided to implement this in psrc_urbansim, instead of Urbansim and Urbansim Defaults. When finished we can decide if we want to move the code to those modules (which would be straightforward) and issue a pull request- UDST might want this functionality.  

- The module binary_discrete_choice.py and it's classes started as a direct copy of the dcm module. I have changed only the code necessary to make binary logit estimation work. The next step is to make it work for simiulation. After that, unused code will need to be stripped out and comments/doc strings will need to be updated. I am going to be on vacation next week so I wanted to commit what I have done so far.

**Comment by stefancoe** [comment]
@bricegnichols- if you work on this next week, I created a simulation step that has prototype code showing how it could be implemented. It beings on line 80 of [workplace_models.py](https://github.com/psrc/urbansim2/blob/stefan_dev/psrc_urbansim/workplace_models.py)

Thanks!

**Comment by stefancoe** [comment]
I have implemented simulation in binary_discrete_choice here:
https://github.com/psrc/urbansim2/commit/5a6ca92ecd5288c998705b321b8366fe79ef8cc8 

And a wahcm here:
https://github.com/psrc/urbansim2/commit/cca56d18b6cf3ca8965e044d48ad86ce2da6919c

**Comment by stefancoe** [comment]
@hanase Suzanne and I spent some time last week getting familiar with how work at home operates during simulation years in Urbansim1. If I understand correctly, the wahcm calculates the probability of work at home for each worker (who are not currently assigned a job) and then a separate step is used to assign workers to home-based jobs in their TAZ- using the probabilities from the wahcm.  This ensures an even match between work at home workers and home-based jobs. If we are on the right track, maybe we should try to implement the same logic in urbansim2.

**Comment by hanase** [comment]
Here is how it currently works in Opus:
1. It calculates the probabilities using a binary logit. 
2. Using these probabilities it samples as many workers as there are home-based jobs. (This is optional in the code, but it's turned on in our runs.)
3. Then there are two variants:
   3a. It randomly assigns those jobs to the selected workers.
   3b. It connects workers to jobs randomly selected within specified geography of the workers home location.
4. The building_id of the jobs is set to the home location of the corresponding workers.

For the base year run, we use 3b on census-tract level, so that the baseyear job counts are not too destroyed. For all future years we use 3a.

**Comment by stefancoe** [comment]
Thanks @hanase! Here is the commit for my attempt at implementing what you describe above: https://github.com/psrc/urbansim2/commit/4d520e68e3182bb2593605d02a03907a50b76f1b

Here is an outline of the steps I took:

- Run WAHCM for workers that have not been assigned a job ( job_id==-1, employment_status>0)
- WAHCM returns the probabilities to work at home for those workers
- For said workers, sample the number of workers == number of home-based jobs not filled using the probabilities as a weight. 
- Merge the indexes of the sampled workers and the unfilled home-based jobs into a DF (they should be the same length). Use this to update job_id on the persons table and building_id on the jobs table. Since the job's building_id gets updated to the persons household building_id, I assume it does not matter which person gets which job and vise versa.

**Comment by stefancoe** [comment]
@hanase- A couple of things:

- In the latest opus Urbansim run, in 2014 there are 117,897 jobs that are home-based, but 168,692 persons that are wok_at_home. 

- By 2050, this becomes 209,067 & 230,300 respectively. 

Based on the logic described above, it seems that the number of home-based jobs dictates how many persons are work at home throughout the simulation, but that does not seem to be happening.  

Also, when a person gets disconnected from a job that is home-based, should there work-at_home status return 0? Since their job_id is -1 they would be in the pool of workers that get run thrugh the WACM. 

Thanks!

**Comment by hanase** [comment]
@stefancoe - it shouldn't be a problem in opus-urbansim, since anytime we use the work_at_home attribute we interact it with the fact if the worker has a job. For example, the agent filter for workplace choice model is person.is_non_home_based_worker_without_job. So if you count the numbers above as persons.work_at_home & persons.job_id > 0 (which is the way it's used) there shouldn't be any discrepancy. But if it's more convenient for urbansim2 to set workers without job to work_at_home to 0 that's fine.

**Comment by stefancoe** [comment]
Thanks @hanase! Did you see my other comment above describing my commit for implementing work at home? I am starting to think that my method of assigning work_at_home workers  to home_based jobs needs to be randomized (see 4th bullet point).

**Comment by hanase** [comment]
Sorry I missed that comment. It looks good. Yes - the assignment needs to be randomized. You can use the same order of workers as it comes out of the sampling procedure in step 3 and do the merge while using that ordering.

**Comment by stefancoe** [comment]
@hanase - I think this is correctly implemented in @orca.step('wahcm_simulate') in [work_place_models.py](https://github.com/psrc/urbansim2/blob/stefan_dev/psrc_urbansim/workplace_models.py). 

This can issue can be closed once code is reviewed.
