### ISSUE TITLE
households_transition step results in records in persons table that do not have related records in households

### ISSUE THREAD

**Issue by stefancoe** [psrc/urbansim2#123]
Edited for clarity

After this step, the Persons table has 6033 records with invalid household_id (no corresponding records in the households table).

**Comment by stefancoe** [comment]
I think I see why this is happening. 

The function/method 'transition' on the TabularGrowthRateTransition class in [transition.py](https://github.com/UDST/urbansim/blob/master/urbansim/models/transition.py) returns updated, added_indexes, copied_indexes, & removed_indexes. Updated is the modified households table that represents existing households & additional households due to growth for a given year, as specified by a control totals file. This file also provides distribution parameters.  

I think the problem starts on lines 305 at the start of the loop that goes through the control totals and makes adjustments to the households: Line 305 creates the variable 'subset'- a subset of 'data', which is the households table:

```python
subset = util.filter_table(data, row, ignore={self._config_column})
```

Line 319 figures out which rows are being added or deleted:

```python
updated, added, copied, removed = \
                add_or_remove_rows(subset, nrows, starting_index, self.accounting_column)
```

Later on, the persons table is updated on line 519:

```python
for table_name, (table, col) in linked_tables.items():
            logger.debug('updating linked table {}'.format(table_name))
            updated_links[table_name] = \
                _update_linked_table(table, col, added, copied, removed)
```

The problem, I think, is that it is possible that an existing household, say household_id 878, never gets picked as part of the variable 'subset'. Since 'added', 'copied' and 'removed' are all based on the variable subset, household 878 is not dealt with (removed from persons) because it was never picked on line 305. This household is no longer in the households table because the housholds table is set to updated, which was created from subset on line 319.

The actual updating occurs in [utils](https://github.com/UDST/urbansim_defaults/blob/master/urbansim_defaults/utils.py)

On line 580:
```python
model = transition.TransitionModel(tran)
    new, added_hh_idx, new_linked = model.transition(hh, year, linked_tables=linked_tables)
    new.loc[added_hh_idx, location_fname] = -1
    print "Total agents after transition: {}".format(len(new))
    orca.add_table(agents.name, new)
    for table_name, table in new_linked.iteritems():
        print "Total %s after transition: %s" % (table_name, len(table))
        orca.add_table(table_name, table)
```
where agents.name is 'households' and new is 'updated'. And orca.add_table(table_name, table) is adding the modified persons table, which still has household_id 878, which is no longer in households.

**Comment by stefancoe** [comment]
Yes- it turns out the missing households have an income of 49,999 or 74,999 so this is a problem with our control totals.

**Comment by msimonson-psrc** [comment]
We have our control totals as 0 to 49,999 ... 50,000 to 74,999 .... 75,000 to 99,999 ... and 100,000 up to Infinity.  Assuming all income values are integers, that would mean that the max ends of the ranges are being interpreted exclusively?  IE we should list them as 0 to 50,000 ... 50,000 to 75,000 ... etc.?  And probably a fluke that no HHs with income of $99,999 also in the missing?

**Comment by stefancoe** [comment]
Thanks Mark. And no fluke, just me not looking far enough down the table. Households with an income of 99,999 are in there as well.

**Comment by stefancoe** [comment]
@msimonson-psrc- Here is an example of one of the queries from the code. So it looks like >= is used for the min and < is used for the max. 
'income < 99999.0 and income >= 75000.0 and persons < 1.5 and persons >= 1.0 and workers < 0.5 and workers >= 0.0'

**Comment by msimonson-psrc** [comment]
What's best fix, code change or input change?  Feels more intuitive to me to leave the ranges in input table inclusive, and make it "income <= 99999.0 and income >= 75000.0 and ... "  But might just be me, I'm open. 
Hana, this in our current/opus version of code too?

**Comment by hanase** [comment]
In Opus, I think it's done the way you say, but that has the disadvantage that you could not use continuous values (it presumes integers). I think in order to be able to use the urbansim2 code without modifications, we need to make changes in the control totals table. We could change the Opus code to work the same way, so that we don't need two versions of the table.

**Comment by hanase** [comment]
I realized I already made changes to the control totals used in urbansim2, namely for workers and persons, as it would not work when both min and max are the same number. So for example for households with 1 persons, we need to have min 1 and max e.g. 1.5. I did not do this change for income. Stefan, I'm wondering if we could have a little script that would do these changes on the fly during the conversion into the h5 file, so that we don't need to do data and code changes in Opus.

**Comment by stefancoe** [comment]
Hana- that sounds good to me.

**Comment by stefancoe** [comment]
Fixed with this commit:
https://github.com/psrc/urbansim2/commit/3246899996c0777d02e3c6bc60969840c08712bd

**Comment by hanase** [comment]
@stefancoe - this change has been made into cache_to_hdf5.py, but not into  	estimation_cache_to_hdf5.py, which is going to be the main conversion script, for both, simulation and estimation, right?

**Comment by stefancoe** [comment]
This is all covered by [one conversion script](https://github.com/psrc/urbansim2/blob/stefan_dev/data/conversion/cache_to_hdf5.py)
