### ISSUE TITLE
New persons resulting from household_transition step should not have job_ids

### ISSUE THREAD

**Issue by stefancoe** [psrc/urbansim2#126]
Because new persons are cloned, their job_id field maybe populated. Make sure to set job_id to -1 for any  new persons.

**Comment by stefancoe** [comment]
Added code to households_transition step in models.py to take care of this:

https://github.com/psrc/urbansim2/commit/dd968d6aea53c3558c06f28ad5e9a289b904aa15

**Comment by hanase** [comment]
Looks good to me. Thanks Stefan!
