### ISSUE TITLE
In conversion script pass YEAR via an argument

### ISSUE THREAD

**Issue by hanase** [psrc/urbansim2#132]
In the [cache2h5 conversion script](https://github.com/psrc/urbansim2/blob/stefan_dev/data/conversion/estimation_cache_to_hdf5.py) make it possible to set the year as an argument, instead of hard-coded in the [YEAR](https://github.com/psrc/urbansim2/blob/stefan_dev/data/conversion/estimation_cache_to_hdf5.py#L74) object. E.g. via an option '-y'. It can use 2014 as default.

In an estimation mode, the -y option could be given as a sequence, e.g. `-y 2000,2009,2014` with these three values as default.

**Comment by stefancoe** [comment]
This should take care of it:
https://github.com/psrc/urbansim2/commit/a0a31cb40281a1d3cc032307c51cb111b22915d9

**Comment by hanase** [comment]
@stefancoe - I'm not able to pass the year value. I get this error:

$ python cache_to_hdf5.py //modelsrv8/d$/opusgit/urbansim_data/data/psrc_parcel/base_year_2014_inputs/urbansim2_estimation_cache test.h5 ["2000", "2009", "2014"] --is-estimation
usage: cache_to_hdf5.py [-h] [--is-estimation] [--no-compress]
                        base_dir hdf_name year
cache_to_hdf5.py: error: unrecognized arguments: 2009, 2014]

**Comment by stefancoe** [comment]
@hanase the code worked when I had the arguments in a list in Main(), but clearly its not working when passing them in the command prompt. I wonder if it would be easier to just have some variables like year and path the top of the script instead of using argparse?

**Comment by hanase** [comment]
Sure. Make it simple for now - we can revisit later.
