### ISSUE TITLE
Implement filtering of valueable proposals in developer model

### ISSUE THREAD

**Issue by hanase** [psrc/urbansim2#143]
In the feasibility part of the developer model one can configure how many proposals per parcel to advance into the global selection. We need to filter out only proposals within a certain percentage of the maximum profit on parcels, e.g. 65%. This would go to the end of the [run_feasibility](https://github.com/psrc/urbansim2/blob/a6358863b907ac5a88828172440ba2b36fd44108/psrc_urbansim/developer_models.py#L173) function.

**Comment by stefancoe** [comment]
@hanase- I can take this on.

**Comment by stefancoe** [comment]
@hanase I have this working, but I had to make changes to the [sqftproforma](https://github.com/UDST/developer/blob/master/developer/sqftproforma.py) class in developer. I'll go ahead and fork this repo so we can issue a pull request with our changes.
