### ISSUE TITLE
In the developer model allow multiple buildings per parcel

### ISSUE THREAD

**Issue by hanase** [psrc/urbansim2#146]
A big issue with the developer model is that it builds only one building per parcel. Thus, one cannot distinguish between different types of units on mix-use parcels, e.g. when multiple components are all non-residential or all residential. Can we modify the model to allow multiple buildings per parcel?

**Comment by stefancoe** [comment]
@hanase- Are there two problems here? 1) that the developer model will not build a building with both residential and non residential units. And 2) that developer model cannot build more than one building? 

Also, I noticed the following parameter on the developer constructor and was wondering if it does anything to solve these this issue:

drop_after_build : bool
        Whether or not to drop parcels from consideration after they
        have been chosen for development.  Usually this is true so as
        to not develop the same parcel twice.

**Comment by hanase** [comment]
@stefancoe, regarding 1), the feasible forms can have both components, res and non-res on the same parcel. But the selection in the developer model happens either on the basis of residential units or job spaces. I believe how it works is that a form with both components can be built if it makes it through the selection on the basis of one of its components. But if such a form does make it through, it is represented as one building which has both, residential  units and non-res sqft. 

I think we still want the drop_after_build argument to be True. It causes the selected forms to be deleted from the feasibility dataset. As I understand it, if it would not be deleted, the same buildings would be built multiple times. 

What we need here is, after a form is selected, to split it into multiple buildings.

And we need to somehow make the selection process to work for res and non-res together.

**Comment by stefancoe** [comment]
@hanase Thanks- this helps a lot!

**Comment by hanase** [comment]
Now when the res and non-res developer models can run together, implement a decomposition into buildings as the first step in the [add_buildings](https://github.com/psrc/urbansim2/blob/28333bdde9f6b590c287f65952aa7d5e729d88a6/psrc_urbansim/developer_models.py#L206) function.

**Comment by hanase** [comment]
This is now done in [disaggregate_buildings](https://github.com/psrc/urbansim2/blob/d724aa51c6562655b202304c6ed183a19e3eb735/psrc_urbansim/developer_models.py#L216).
