### ISSUE TITLE
Speed up REPM

### ISSUE THREAD

**Issue by hanase** [psrc/urbansim2#155]
REPM takes ages and eats lots of memory because it uses the `to_frame()` method, which computes ALL variables defined for the parcels dataset, even those that are not used. Can we somehow automatically determine which variables are needed and pass it to the model?

Also regarding REPM, see #140 and #139.

**Comment by stefancoe** [comment]
@hanase I looked into this and it seems like the [to_frame()](https://github.com/UDST/urbansim_defaults/blob/master/urbansim_defaults/utils.py#L166) method that is being used is from urbansim_defaults, which extracts the columns (via cfg) that are used in the model and includes them when calling the orca.merge_columns method.

Still, it does take a long time.

**Comment by hanase** [comment]
You're right @stefancoe - I missed it.
