### ISSUE TITLE
Variable vacant_jobs returns an array of the wrong size

### ISSUE THREAD

**Issue by hanase** [psrc/urbansim2#177]
@stefancoe , could you please look into this? The variable is returning an array of a different size than the size of the jobs dataset. 
https://github.com/psrc/urbansim2/blob/dev/psrc_urbansim/vars/variables_jobs.py#L83

**Comment by stefancoe** [comment]
Sure- I'll change it back to the way I had it and hopefully that will fix it.

**Comment by stefancoe** [comment]
@hanase Did you have the 'update_persons_jobs' step on after the jobs transition/relocation steps?

**Comment by hanase** [comment]
I didn't. But now I see you fixed the variable - thanks so much @stefancoe ! I do think that it is the responsibility of the variables to return arrays of the right size.
